# Xremap configuration for macOS-like key mappings on Ubuntu/Linux
# Based on Kinto project mappings

# Global modifier remapping - makes Super key work like on macOS
modmap:
  - name: Global modmap - Make Super key work like macOS
    application:
      not: 
        - alacritty
        - gnome-terminal
    remap:
      # Uncomment one of the following sections based on your keyboard layout preference:
      
      # Default Mac/Win layout
      # Alt_L: Ctrl_R        # Make Alt work like Super
      # Super_L: Alt_L       # Make Super work like Alt  
      # Ctrl_L: Super_L      # Make Ctrl work like Super
      
      # Mac Only layout (recommended for macOS users)
      # Super_L: Ctrl_R      # Make Super work like Ctrl
      # Ctrl_L: Super_L      # Make Ctrl work like Super

keymap:
  # IntelliJ IDEA / JetBrains IDEs
  - name: IntelliJ IDEA keybindings
    application:
      only: [/jetbrains-.*/]
    remap:
      # General
      Super-0: Alt-0
      Super-1: Alt-1
      Super-2: Alt-2
      Super-3: Alt-3
      Super-4: Alt-4
      Super-5: Alt-5
      Super-6: Alt-6
      Super-7: Alt-7
      Super-8: Alt-8
      Super-9: Alt-9
      Super-comma: Ctrl-Alt-s
      Super-semicolon: Ctrl-Alt-Shift-s
      # File operations
      Super-n: Ctrl-Alt-Insert        # Create new file
      Super-Shift-n: Ctrl-Shift-n     # Search for file/class
      Super-F4: Ctrl-F4               # Close current project/process
      # Navigation - Back and Forward
      Super-Alt-left: Ctrl-Alt-left   # Navigate back
      Super-Alt-right: Ctrl-Alt-right # Navigate forward
      # Debugging
      Super-Alt-r: F9
      # Search/Replace
      Super-g: F3
      Super-Shift-F3: Shift-F3
      Super-Ctrl-g: Ctrl-Alt-Shift-j
      # Editing
      Super-space: Ctrl-space
      Super-Shift-space: Ctrl-Shift-space
      Super-j: Ctrl-q
      Super-o: Ctrl-o
      Super-i: Ctrl-i
      Alt-up: Ctrl-w
      Alt-down: Ctrl-Shift-w
      Super-Alt-o: Ctrl-Alt-o
      Super-Alt-i: Ctrl-Alt-i
      Super-backspace: Ctrl-y
      Super-w: Ctrl-F4
      # Navigation
      Super-Shift-o: Ctrl-Shift-n
      Super-l: Ctrl-g
      Alt-space: Ctrl-Shift-i
      Super-Y: Ctrl-Shift-i
      # VCS
      Super-v: Alt-grave

  # File Managers - Nautilus only
  - name: Nautilus - macOS Finder-like shortcuts
    application:
      only: [nautilus, org.gnome.nautilus]
    remap:
      # File properties and preferences
      Super-i: Alt-enter
      Super-comma: Ctrl-comma
      Super-Shift-period: Ctrl-h
      # Navigation
      Super-left_brace: Alt-left
      Super-right_brace: Alt-right
      Super-left: Alt-left
      Super-right: Alt-right
      Super-up: Alt-up
      Super-down: enter
      Super-Shift-left_brace: Ctrl-Page_up
      Super-Shift-right_brace: Ctrl-Page_down
      Super-Shift-left: Ctrl-Page_up
      Super-Shift-right: Ctrl-Page_down
      # View modes
      Super-1: Ctrl-2
      Super-2: Ctrl-1
      # File operations
      Super-Ctrl-o: Shift-enter
      Super-backspace: delete

  # Web Browsers - General
  - name: Web Browsers - macOS Safari-like shortcuts
    application:
      only:
        - Brave-browser
        - Chromium
        - Chromium-browser
        - Firefox
        - Firefox Developer Edition
        - Google-chrome
        - microsoft-edge
        - microsoft-edge-dev
    remap:
      Super-q: Ctrl-q
      Alt-Super-i: Ctrl-Shift-i
      Alt-Super-j: Ctrl-Shift-j
      Super-1: Alt-1
      Super-2: Alt-2
      Super-3: Alt-3
      Super-4: Alt-4
      Super-5: Alt-5
      Super-6: Alt-6
      Super-7: Alt-7
      Super-8: Alt-8
      Super-9: Alt-9
      Super-Shift-left_brace: Ctrl-Page_up
      Super-Shift-right_brace: Ctrl-Page_down
      Super-Alt-left: Ctrl-Page_up
      Super-Alt-right: Ctrl-Page_down
      Ctrl-Page_up: Ctrl-Page_up
      Ctrl-Page_down: Ctrl-Page_down

  # Firefox specific
  - name: Firefox specific mappings
    application:
      only: [Firefox]
    remap:
      Super-comma: [Ctrl-t, a, b, o, u, t, Shift-semicolon, p, r, e, f, e, r, e, n, c, e, s, enter]
      Super-Shift-n: Ctrl-Shift-p

  # Chrome-based browsers specific
  - name: Chrome-based browsers
    application:
      only:
        - Brave-browser
        - Chromium
        - Chromium-browser
        - Google-chrome
        - microsoft-edge
        - microsoft-edge-dev
    remap:
      Super-comma: [Alt-e, s, enter]
      Super-q: Alt-F4
      Super-left_brace: Alt-left
      Super-right_brace: Alt-right

  # VS Code / Codium
  - name: VS Code - macOS-like shortcuts
    application:
      only: [code, vscodium]
    remap:
      Super-space: Ctrl-space
      # Override global Super+period
      Super-period: Super-period
      # Wordwise with Alt-F19 hack to prevent Alt menu activation
      Alt-left: [Alt-F19, Ctrl-left]
      Alt-right: [Alt-F19, Ctrl-right]
      Alt-Shift-left: [Alt-F19, Ctrl-Shift-left]
      Alt-Shift-right: [Alt-F19, Ctrl-Shift-right]
      # Tab navigation
      Ctrl-Alt-left: Ctrl-Page_up
      Ctrl-Alt-right: Ctrl-Page_down
      Super-Shift-left_brace: Ctrl-Page_up
      Super-Shift-right_brace: Ctrl-Page_down
      # VS Code specific shortcuts
      Super-g: F3
      Super-Shift-g: Shift-F3
      Ctrl-Alt-f: Ctrl-h
      Ctrl-Alt-e: Ctrl-Shift-h

  # Sublime Text
  - name: Sublime Text - macOS-like shortcuts
    application:
      only: [Sublime_text, subl]
    remap:
      Super-space: Ctrl-space
      Ctrl-Super-up: Alt-o
      Super-Ctrl-f: F11
      Ctrl-Alt-v: [Ctrl-k, Ctrl-v]
      Ctrl-Alt-up: Ctrl-up
      Ctrl-Alt-down: Ctrl-down
      Super-Shift-up: Alt-Shift-up
      Super-Shift-down: Alt-Shift-down
      Ctrl-Shift-left_brace: Ctrl-Page_down
      Ctrl-Shift-right_brace: Ctrl-Page_up
      Ctrl-Alt-right: Ctrl-Page_down
      Ctrl-Alt-left: Ctrl-Page_up

  # ULauncher
  - name: ULauncher - Remap Super keys to Alt
    application:
      only: [ulauncher]
    remap:
      Super-1: Alt-1
      Super-2: Alt-2
      Super-3: Alt-3
      Super-4: Alt-4
      Super-5: Alt-5
      Super-6: Alt-6
      Super-7: Alt-7
      Super-8: Alt-8
      Super-9: Alt-9
      Super-0: Alt-0
      Super-b: Alt-b
      Super-d: Alt-d
      Super-e: Alt-e
      Super-f: Alt-f
      Super-g: Alt-g
      Super-h: Alt-h

  # Terminal applications - Alacritty and GNOME Terminal only
  - name: Terminal overrides for wordwise navigation
    application:
      only: [alacritty, gnome-terminal]
    remap:
      Alt-backspace: Alt-Shift-backspace
      Alt-delete: [escape, d]
      Super-backspace: Ctrl-u
      Super-delete: Ctrl-k
      # Tab navigation for terminals
      Super-Shift-left: Ctrl-Page_up
      Super-Shift-right: Ctrl-Page_down

  # Global keymaps (excluding terminals and remotes)
  - name: Global macOS-like shortcuts
    application:
      not:
        - alacritty
        - gnome-terminal
        # Remote desktop clients
        - Gnome-boxes
        - org.remmina.Remmina
        - remmina
        - qemu-system-.*
        - qemu
        - Spicy
        - Virt-manager
        - VirtualBox
        - VirtualBox Machine
        - xfreerdp
        - Wfica
        - Anydesk
    remap:
      # Global shortcuts
      Super-period: escape
      Super-Shift-left_brace: Ctrl-Page_up
      Super-Shift-right_brace: Ctrl-Page_down
      Super-space: Alt-F1
      Super-F3: Ctrl-d
      Super-Ctrl-f: Alt-F10
      Super-q: Alt-F4
      Super-h: Ctrl-h
      Super-tab: Alt-tab
      Super-Shift-tab: Alt-Shift-tab
      Super-grave: Alt-grave
      Super-Shift-grave: Alt-Shift-grave
      Ctrl-tab: Ctrl-tab
      Ctrl-Shift-tab: Ctrl-Shift-tab
      
      # Text navigation and selection - macOS style
      Super-left: home
      Super-Shift-left: Shift-home
      Super-right: end
      Super-Shift-right: Shift-end
      Super-up: Ctrl-home
      Super-Shift-up: Ctrl-Shift-home
      Super-down: Ctrl-end
      Super-Shift-down: Ctrl-Shift-end
      
      # Emacs-style navigation
      Ctrl-a: home
      Ctrl-e: end
      Ctrl-b: left
      Ctrl-f: right
      Ctrl-n: down
      Ctrl-p: up
      Ctrl-k: [Shift-end, backspace]
      Ctrl-d: delete
      
      # Word-wise navigation and deletion
      Ctrl-backspace: Ctrl-backspace
      Ctrl-delete: Ctrl-delete
      Alt-backspace: Ctrl-backspace
      Super-backspace: Ctrl-Shift-backspace
      Alt-delete: Ctrl-delete

  # Wordwise navigation (not for VS Code, which has special handling)
  - name: Wordwise navigation - not VS Code
    application:
      not: [code, vscodium]
    remap:
      Alt-left: Ctrl-left
      Alt-Shift-left: Ctrl-Shift-left
      Alt-right: Ctrl-right
      Alt-Shift-right: Ctrl-Shift-right

  # Terminal-specific applications with macOS-like mappings
  - name: Terminal applications - macOS-like shortcuts
    application:
      only: [alacritty, gnome-terminal]
    remap:
      Ctrl-Super-f: Alt-F10
      # Tab switching
      Ctrl-tab: Ctrl-Page_down
      Ctrl-Shift-tab: Ctrl-Page_up
      Ctrl-grave: Ctrl-Page_up
      # Tmux navigation
      Super-t: [Ctrl-a, c]              # Create new tmux window (Ctrl-A + C)
      Super-Alt-left: [Ctrl-a, p]       # Previous tmux window (Ctrl-A + P)
      Super-Alt-right: [Ctrl-a, n]      # Next tmux window (Ctrl-A + N)
      # Terminal shortcuts using Super + Ctrl-Shift
      Super-minus: Ctrl-minus
      Super-equal: Ctrl-Shift-equal
      Super-w: Ctrl-Shift-w
      Super-n: Ctrl-Shift-n
      Super-Shift-left_brace: Ctrl-Page_up
      Super-Shift-right_brace: Ctrl-Page_down
      Super-c: Ctrl-Shift-c
      Super-v: Ctrl-Shift-v
      Super-f: Ctrl-Shift-f
      Super-period: Ctrl-c

  # Alacritty specific
  - name: Alacritty specific
    application:
      only: [alacritty]
    remap:
      Super-k: Ctrl-l 